### ISSUE TITLE
How did you generate the favicons?

### ISSUE THREAD

**Issue by matthiaslischka** [joshgerdes/jekyll-uno#103]
Hi @joshgerdes,
how did you generate the favicons? Which tool did you use?
I would like to add custom favicons without writing the manifest by hand or change any code.

Thx and BR
Matthias

**Comment by joshgerdes** [comment]
It has been awhile but if memory serves I used: https://realfavicongenerator.net

**Comment by matthiaslischka** [comment]
Hmm, tried the same page but it does not generate nearly as many files and e.g. no `manifest.json`.

Maybe we can simplify this and document a clean way to exchange the favicon? I think this is a pretty common task when adopting a template and right now its about 30 files that need to be somehow dealt with.

**Comment by Arszilla** [comment]
I used the site @joshgerdes mentioned to make my favicons but it doesn't generate all the icons present in `/images/favicons`. Would there still be favicons even without all the icons present in the current folder?
