### ISSUE TITLE
Update Jekyll to 3.7 gain livereload

### ISSUE THREAD

**Issue by edwinthinks** [joshgerdes/jekyll-uno#104]
Hello,

I was wondering if there were plans to update Jekyll to [3.7.](https://jekyllrb.com/news/2018/01/02/jekyll-3-7-0-released/). I found the new `livereload` feature to be a big time saver :)

Thanks! Love this theme!

**Comment by joshgerdes** [comment]
Feel free to open a PR, not sure when I will get to it.

**Comment by edwinthinks** [comment]
@joshgerdes okie =)
