### ISSUE TITLE
Change Permalink from "/#blog" to "/blog/"

### ISSUE THREAD

**Issue by BayuAngora** [joshgerdes/jekyll-uno#105]
Dear All 

I love this theme because it's fast and simple. 

I want to change my blog permalink from default username.github.io/#blog to username.github.io/blog/ 

So, when I have a lot of posts, it can be paginated through /blog/, /blog/page2, /blog/page3, etc. 

I try to fill my blog.html file with this code ->
https://github.com/BayuAngora/BayuAngora.github.io/blob/master/_pages/blog.html 

But the post list can't be paginated. Can you help me?

**Comment by Arszilla** [comment]
Have you found a solution to this? I'm trying to achieve the same task on my end as I am adding a `Projects` page.
