### ISSUE TITLE
Font/Background Color in Code Blocks

### ISSUE THREAD

**Issue by Arszilla** [joshgerdes/jekyll-uno#106]
Is there a way to change these? When I paste a simple text, it is too unreadable IMO and I'd like the text to be white if possible.

**Comment by JordyValentine** [comment]
the styling for the code blocks is in `_sass/uno.scss` around line 1020

`
code {
padding: .1em .4em;
background: #e8f2fb;
border: 1px solid #c9e1f6;
border-radius: 3px;
font-family: Consolas, Menlo, Monaco, Lucida Console, Liberation Mono, DejaVu Sans Mono, Bitstream Vera Sans Mono, Courier New, monospace, serif;
font-size: .85em; }`
