### ISSUE TITLE
Unable to load blog post

### ISSUE THREAD

**Issue by saifullah73** [joshgerdes/jekyll-uno#110]
There is an issue, where if you update the post date beyond the year 2019, i.e 2020 and onward, the post does not show up on the post list. Does anyone else has a similar issue, if so, whats the solution.

**Comment by JordyValentine** [comment]
This is not an issue, but rather a feature of Jekyll. Posts dated in the future are considered unpublished and aren't generated when your Jekyll site is built.

Using `jekyll serve --future` will display the post in your local build, adding `future: false` to your _config.yml will keep future posts hidden from the live version.
Adding `future: true` to your _config.yml will ignore the future date and treat the post like any other

Some useful info
- [https://jekyllrb.com/docs/configuration/options/#build-command-options](https://jekyllrb.com/docs/configuration/options/#build-command-options) - Jekyll build options
- [https://jekyllrb.com/docs/posts/#drafts](https://jekyllrb.com/docs/posts/#drafts) - Jekyll drafts
