### ISSUE TITLE
Resize profile.jpg

### ISSUE THREAD

**Issue by LukeShortCloud** [joshgerdes/jekyll-uno#118]
Is there any way to resize the `_site/images/profile.jpg` circle to be bigger? I added my own custom image. It looks fine on phones and can be too small on computers.

**Comment by joshgerdes** [comment]
You can play with the `width` and `height` in the css to adjust the size

https://github.com/joshgerdes/jekyll-uno/blob/df17cb72ca8142c37bb1830fc01df0e2e8bd50f1/css/main.scss#L52-L59

**Comment by LukeShortCloud** [comment]
@joshgerdes Thank you so much for the quick response! I was previously looking in the wrong CSS files. Adjusting those values works perfectly!
