### ISSUE TITLE
Jekyll-uno displaying improperly and not functioning properly on mobile

### ISSUE THREAD

**Issue by MatthewThomasMiller** [joshgerdes/jekyll-uno#119]
I noticed recently that my Jekyll-uno site (https://matthewthomasmiller.github.io/) has stopped displaying and functioning properly on mobile devices. Previously it worked fine.

On desktop it looks like this:
![screenshot](https://user-images.githubusercontent.com/13054157/103793970-2a0c1380-5012-11eb-9595-c82b4d4a8a01.jpg)

But on mobile it looks like this:
![Matthew Thomas Miller](https://user-images.githubusercontent.com/13054157/103792683-d13c7b00-5011-11eb-90e6-f8b852f03c23.png)

In addition to the buttons linking to bio, twitter, etc. not showing up, you also cannot click on the expansion bar at the top on the mobile version. Any ideas what is going on? Is it a wider problem with Jekyll-uno or something that just has happened to mine?

**Comment by joshgerdes** [comment]
I'm not sure why you are having issues with the menu not working in mobile for your implementation.  But the difference in layout from desktop and mobile (less buttons, etc.) is by design.

You can visit the [demo page](http://joshgerdes.com/jekyll-uno/) to see the expected behavior and layout.

**Comment by MatthewThomasMiller** [comment]
@joshgerdes, thanks. Yes, I know the difference is intended. I see the demo works fine. I am just at a complete loss for why this would stop working on my implementation. Has anyone else experienced this issue before? Do you have any suggestions on where in the code something could have gone wrong (so I can compare it)?

**Comment by joshgerdes** [comment]
This is the click event code for the mobile menu:
https://github.com/joshgerdes/jekyll-uno/blob/master/js/main.js#L30-L33

And it looks like your `js/main.js` file has duplicate code in it which could be the cause.

**Comment by MatthewThomasMiller** [comment]
Brilliant, thank you so much! 

Removing that duplicate code did the trick. I seriously have no idea how that go in there.

Thanks for the great theme.
