### ISSUE TITLE
The Blog Button is not work?

### ISSUE THREAD

**Issue by Xcode1994** [joshgerdes/jekyll-uno#18]
Hello.
First, thanks for your work,I use this to build my own blog.
But there is something wrong,when I click the blog button which is on the homepage ,there is nothing, this button just not work. how can I fix this problem.

thank you

**Comment by hiimivantang** [comment]
check out this: https://jekyllrb.com/docs/posts/

you are supposed to write your blog posts in markdown and put it in _posts directory. 

Blog button is just for reading the existing blog posts that you save in the _posts directory.....
