### ISSUE TITLE
scrollbar in code bloc

### ISSUE THREAD

**Issue by ymsaout** [joshgerdes/jekyll-uno#21]
Hi,

Is there a simple way to add a scrollbar when a line is too long and fill all the code bloc?  It wrap line for the moment in my example.

Thank you. :)

**Comment by joshgerdes** [comment]
Make these two changes to the [css/main.css](https://github.com/joshgerdes/jekyll-uno/blob/master/css/main.css):

pre.highlight, .highlight pre {
    padding: 10px;
    **overflow: scroll;**
}

pre.highlight code, .highlight pre code {
    ~~white-space: pre-wrap;~~
}

**Comment by ymsaout** [comment]
It works, thanks a lot !
