### ISSUE TITLE
when I run jekyll serve

### ISSUE THREAD

**Issue by francis2211** [joshgerdes/jekyll-uno#22]
Dependency Error: Yikes! It looks like you don't have jekyll-paginate or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- jekyll-paginate' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/!

**Comment by thosakwe** [comment]
```
gem install jekyll-paginate
```

:smile:

**Comment by francis2211** [comment]
@thosakwe I didnt know how to remove this post but that was not the problem :) I found a way to fix the problem!... Thank you.

**Comment by thosakwe** [comment]
@francis2211 There should be a 'close' button somewhere

**Comment by LordRaydenMK** [comment]
I had the same problem and installing jekyll-paginate didn't help.

I run into this SO question http://stackoverflow.com/questions/37055554/jekyll-serve-not-working?rq=1 and it worked for me by executing `bundle exec jekyll serve`

Ruby version: 2.3.1
RubyGems version: 2.6.6
Jekyll version: 3.1.6
