### ISSUE TITLE
Add an "About" button

### ISSUE THREAD

**Issue by jroberayalas** [joshgerdes/jekyll-uno#25]
Hi,

This is the first time I try to use a jekyll template to create a site. I was wondering if it'd be too difficult to create an "About" button next to the "Blog" one that redirects you to a page with the general info about the site.

Thanks!

**Comment by joshgerdes** [comment]
Sure, you could create an about page following this: https://jekyllrb.com/docs/pages/

Then add a link to your about page here: https://github.com/joshgerdes/jekyll-uno/blob/master/_includes/header.html

I am not adding it to the theme though. Thanks!

**Comment by pascalschulthess** [comment]
A quick follow up (I'm also new to jekyll):

I added

```
<li class="navigation__item"><a href="{{ site.baseurl }}/about" title="link to {{ site.title }} about" class="blog-button">About</a></li>
```

to the header and created a `about` folder containing a `index.md` with the following content:

```
---
layout: default
title: "About"
---
text text
```
 But the title is not shown on the page... Would you be so kind and help out?

**Comment by bravina** [comment]
Hi @joshgerdes,

I did add an "About" page, added links to it where appropriate, and everything works nicely. My only issue is that I created a button for it, exactly like the already existing "Blog" button, but it doesn't toggle the animation when clicked: the panel with my "About" page is loaded instantly, without the delay effect (from <code>main.js</code>). How can I fix this?

Thanks!

**Comment by joshgerdes** [comment]
You need to add the animation to the click event for the new button.  Similar to how it works for the blog button.  JS found [here](https://github.com/joshgerdes/jekyll-uno/blob/master/js/main.js).

**Comment by bravina** [comment]
So I can't just write <code>class="blog-button"</code> in <code>_includes/header.html</code> when I define my "about" button?

**Comment by bravina** [comment]
Still haven't found a way to fix my problem :/ I'm wondering if this has to do with what the buttons link to: that `/#blog` is (as far as I understand) automatically generated as a list of posts, whereas `/about.md` will redirect to an actual page.

**Comment by srdg** [comment]
@bravina yes you can do that, but you need to make sure about the content preceding the actual contents of your about page. I'm referring to 
```
---
title:  "About!"
date:   2016-11-11 20:55:23
categories: [jekyll]
tags: [jekyll]
layout: default
---
```
This would render the about page just like it does for the blog.
It took me kind of an hour to figure that out. Putting this here in case someone comes looking.
