### ISSUE TITLE
nokogiri dependency is out of date

### ISSUE THREAD

**Issue by codewithtyler** [joshgerdes/jekyll-uno#26]
The command `bundle install` fails due to the nokogiri dependency being out of date. This is the error I got:

`"An error occurred while installing nokogiri (1.6.7.2), and Bundler cannot
continue.
Make sure that`gem install nokogiri -v '1.6.7.2'`succeeds before bundling."`

 I had to run `gem update nokogiri` before running `bundle install`. If you don't do that then the install command will fail every time.

**Comment by joshgerdes** [comment]
Following the install and test directions resulted in nokogiri 1.6.7.2 being install correctly. Perhaps you already had an old version of nokogiri it was trying to use?

**Comment by codewithtyler** [comment]
I followed the install directions and it tried to install 1.6.7.2 but failed. Now I do have the latest version of ruby installed. That could be the reason why it gave the error.
