### ISSUE TITLE
blog posts are ignoring the layouts

### ISSUE THREAD

**Issue by codewithtyler** [joshgerdes/jekyll-uno#27]
I forked this project got it running locally then copied my blog posts into the _posts folder. When I ran the serve command and clicked on a post I noticed that it wasn't using the post layout. Actually it wasn't using any layout at all. Any ideas?

**Comment by codewithtyler** [comment]
@joshgerdes any idea what might be causing this?

**Edit:** I looked over it some more and here's what I've noticed. It looks like each posts page it looking for the CSS, JS, and images in the wrong directory. Below is the one of the 404 errors I have in my console. Keep in mind my permalinks look like this `/archive/:year/:month/:day/:title/`.  

```
Failed to load resource: the server responded with a status of 404 (Not Found)  http://127.0.0.1:4000/archive/2016/04/10/object-oriented-javascript-for-csharp-developers-part-one/css/main.css
```

Based on that it looks like its adding the permalink url to the src rather than looking for it based on its relation to the root directory.

**Comment by joshgerdes** [comment]
sounds like the 'baseurl' is not defined correctly here:
https://github.com/joshgerdes/jekyll-uno/blob/master/_config.yml#L5

Otherwise, I'd check with the [Jekyll docs](https://jekyllrb.com/docs/home/) to make sure you installed and configured everything correctly.

**Comment by codewithtyler** [comment]
Wouldn't that make my blog load with `http://127.0.0.1:4000/jekyll-uno` instead of just `http://127.0.0.1:4000`

**Comment by joshgerdes** [comment]
baseurl: '/' would make it the root.

**Comment by codewithtyler** [comment]
Thanks, I'll try that out when I get home tonight.

**Comment by codewithtyler** [comment]
Also I wanted to ask, I noticed that your blog starts out with the background image full screen and then only changes to have the blog on the right once you click the blog link. When I load the page using `jekyll serve' it has my blog on the right. Is there something that I need to change in order to get the same effect as your blog?
