### ISSUE TITLE
kramdown

### ISSUE THREAD

**Issue by jacyzin** [joshgerdes/jekyll-uno#3]
Hi, I found this while jekyll build:

Conversion error: Jekyll::Converters::Markdown encountered an error while converting '_posts/2016-01-08-welcome-to-jekyll.markdown':
                    Missing dependency: kramdown
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    Missing dependency: kramdown

Can help?

**Comment by jacyzin** [comment]
root@jacyzin:/jekyll-uno# gem query | grep kramdown
kramdown (1.9.0)

**Comment by p3LZ3r** [comment]
as suggested in http://bundler.io/, try bundle exec

bundle exec jekyll serve --watch

**Comment by joshgerdes** [comment]
Yep, use bundler. This is also setup to work for a GitHub deploy so that's why the gem 'github-pages' is used (which installs kramdown). More info here: https://github.com/github/pages-gem

**Comment by jacyzin** [comment]
Tnx for help, I solve this in the same day, but not interact here.
