### ISSUE TITLE
About categories

### ISSUE THREAD

**Issue by JCarlosR** [joshgerdes/jekyll-uno#34]
Thanks @joshgerdes for the nice theme. I am using jekyll for the first time, and your instructions helped me a lot.

I have a question. I just visit the route /categories/, and it exists, why you don't add one link to this section?

I tried to show the category for each post, but I can't. It seems that jekyll only have a "tags" attribute, but not a "categories" to show with the extract of each post in the index.

**Comment by joshgerdes** [comment]
I setup categories page but don't use them personally so there is not a link.  Feel free to tweak the theme and add a link for your own use if you like.
