### ISSUE TITLE
cannot host with github pages

### ISSUE THREAD

**Issue by serena97** [joshgerdes/jekyll-uno#40]
The website isn't appearing like the demo on my github pages - github pages only shows the html template. I assume that github pages doesn't have the neccessary plugins to host the theme. Since the theme isn't compatible with github pages, what should I use to host it? (beginner in web dev here)

**Comment by joshgerdes** [comment]
Sorry to hear you're having trouble with your installation.  This theme does work on github pages as seen with the [demo](http://joshgerdes.com/jekyll-uno/).

**Comment by bisraelsen** [comment]
@serena97 This most likely has to do with some improperly configured items in your `_config.yml`, double check that file, and make sure all fields are update to reference your personal repository, and not jekyll-uno.
