### ISSUE TITLE
Generating icons

### ISSUE THREAD

**Issue by adishavit** [joshgerdes/jekyll-uno#43]
If I change the profile image, how do I generate all the other icons and favicons?

**Comment by RMBLRX** [comment]
That's not something that's usually built into Jekyll, from my understanding. You'll have to do it manually (or find a plugin, I guess), but there are plenty of sites that can automatically generate a full set of icons from a source image.

**Comment by adishavit** [comment]
Thanks. Can you recommend such sites to do this?
I found [this one](http://realfavicongenerator.net/).

**Comment by RMBLRX** [comment]
I've used [this one](http://www.favicomatic.com), but I couldn't say how complete or incomplete either option is. None of my sites are currently complete by either's standards (probably because my manifest is not quite accurate or up-to-date).
