### ISSUE TITLE
Post width

### ISSUE THREAD

**Issue by adishavit** [joshgerdes/jekyll-uno#48]
How can I make the width of the post page wider?
I want it to retain the same margins, but to stretch to fit the available window page width.
I found several css fields that change this, but i couldn't figure out how to retain the same margins and auto panel hiding for narrower screens.

**Comment by lnishan** [comment]
@adishavit 
You are looking for the CSS property `max-width` :)
If I understand you correctly, all you need to do is just:
Remove all the `max-width` lines in the CSS files and it should get you what you want :)
