### ISSUE TITLE
Add Project Button

### ISSUE THREAD

**Issue by mudit313** [joshgerdes/jekyll-uno#49]
I have added the project button by adding below code in header.html file. The button was created successfully, but was working same as blog button.

```
<nav class="cover-navigation cover-navigation--primary">
            <ul class="navigation">
              <li class="navigation__item"><a href="{{ site.baseurl }}#project" title="link to {{ site.title }} projects" class="project-button">Projects</a></li>
            </ul>
          </nav>
```

You can view my [Project](https://github.com/mudit313/mudit313.github.io) here.

I just want that when I click the button, instead of my blog post it should show some buttons that should direct to the respective project page.
What changes should I make in the project??

**Comment by joshgerdes** [comment]
Please have a look at #25 for more details. In short, it can be done but I do not want to add a specific button to the base theme. Thanks!
