### ISSUE TITLE
Could you add an 'about' page?

### ISSUE THREAD

**Issue by chynl** [joshgerdes/jekyll-uno#54]
I need the ABOUT page to show my info. Thanks.

**Comment by garyscode** [comment]
@stevennl if you look at the list of forks from this repo, there are many of those users who have implemented their own about page (and many other cool features).  For example, the @tradeamateur fork includes an "about" page and can be viewed at http://tradeamateur.github.io .  To see all the members, just click the number by the fork link in the top right of the repository and then click the members button.   Many show the github.io page associated and are easy to copy, paste and view.

**Comment by joshgerdes** [comment]
Please have a look at #25 for more details. In short, it can be done but I do not want to add a specific button to the base theme. @garyscode has some other options that would work as well. Thanks!

**Comment by chynl** [comment]
Thanks!
