### ISSUE TITLE
Having a baseurl of '' doesnt work

### ISSUE THREAD

**Issue by lukemcgregor** [joshgerdes/jekyll-uno#59]
An empty base url is recommended for jekyll hosted at the root of the site but this causes most of the links to break. 
Using '/' makes things mostly work, but there are a few places which result in a // inside the URL (such as inside the feed.xml, and when doing things with plugins like `jekyll-redirect-from`.

This article has some really good instructions on how to do baseurl stuff.
http://downtothewire.io/2015/08/15/configuring-jekyll-for-user-and-project-github-pages/

**Comment by tomajask** [comment]
@lukemcgregor Thanks, the solution from downtothewire.io works as expected!

**Comment by ghost** [comment]
Thanks @lukemcgregor, your solution worked beautifully !
