### ISSUE TITLE
Local Jekyll serve different from github pages output

### ISSUE THREAD

**Issue by pratik1105** [joshgerdes/jekyll-uno#72]
![github](https://user-images.githubusercontent.com/9898287/28408432-0b826ff2-6d55-11e7-903a-de46f679ea2a.png) 
The above is what I get when github pages hosts the website.(This is what I get on the homepage, NOT after clicking on Blog)

![localjekyll](https://user-images.githubusercontent.com/9898287/28408476-38ae82ea-6d55-11e7-8798-808d42dbac03.png)
This is what I get when I do a bundle exec jekyll serve. 
I can't seem to figure out why this happens.

Also, on the github.io site, clicking on any post leads here.
![post](https://user-images.githubusercontent.com/9898287/28408569-8e88fcd6-6d55-11e7-8752-915b96bdd9f9.png)

It was fine about a week ago. I noticed this yesterday.
It seems like the CSS/JS is not working on the github pages hosted site. Any ideas why ?

**Comment by alvarmaciel** [comment]
The same happens to me. I think that is a problem in the setting of the urlbase variable of _config.yml

**Comment by pratik1105** [comment]
@alvarmaciel Indeed it is. I have managed to make it work temporarily using absolute url instead of a relative one for urlbase. Replace your urlbase with "https://username.github.io/[repo]/" or "https://username.github.io" if it is not a separate project. Also inside the main.js file replace the use of urlbase with "/".
This would allow you to get the JS and CSS running on the github server.

**Comment by alvarmaciel** [comment]
Hi @pratik1105 I made the changes proposed on the pull request #71 and all work like charm!

**Comment by dotps1** [comment]
all of the changes in pull request #71 fixed it for me as well.  however, it is in its root site, so my config looks like this
```
url: 'https://myuser.github.io'
baseurl: ''
```

thanks was driving me crazy!

**Comment by joshsoucie** [comment]
Fixed for me as well.

Like dotps1, sent my baseurl to a null string.

If you change all these lines of code yourself, make sure to double and triple check your liquid tags, quotes, and double quotes...

I spent about an hour chasing down what I'd messed up.

**Comment by brohaut** [comment]
Thanks all, same issue, same fix using [https://github.com/joshgerdes/jekyll-uno/pull/71/commits/fb5f7cfd4bac268b0fe770b01b2d3ed22ea14a7f](url) and baseurl: ''
