### ISSUE TITLE
Not able to upload  css in custom domain

### ISSUE THREAD

**Issue by girishnayak12** [joshgerdes/jekyll-uno#73]
I have done following updates in _config.yml
title: Jekyll-Uno
description: 'Jekyll-Uno - a minimal, responsive theme for Jekyll'
url: 'http://girish.world/'
baseurl: '/'

What i can see in landing page is http://girish.world
<img width="1440" alt="screenshot 2017-07-23 17 21 06" src="https://user-images.githubusercontent.com/7499390/28499097-64d20554-6fcb-11e7-8bed-a78a843e45ce.png">

Also When i click on blog link , css is not getting loaded.  Here is screen shot and link http://girish.world/2016/welcome-to-jekyll/
<img width="1440" alt="screenshot 2017-07-23 17 25 09" src="https://user-images.githubusercontent.com/7499390/28499128-ee4066f0-6fcb-11e7-87de-46ed9885ff7f.png">

which is not the desired output. It was working fine without custom domain. 
What i can understand is there is some path issue but i am not able to figure out. I tried lot of permutation and combination .. but no luck.

**Can you help me?**

**Comment by dotps1** [comment]
this looks exactly like #72, check it out!

**Comment by joshsoucie** [comment]
Update from master (pull request #71) and update us.
