### ISSUE TITLE
 how to get rid of extra '/' in the url

### ISSUE THREAD

**Issue by Akatsuki06** [joshgerdes/jekyll-uno#75]
While visiting  post from the tags the url becomes http://127.0.0.1:4000/jekyll-uno//2016/welcome-to-jekyll/
(Note the extra '**/**')
How can it be resolved?? 
![image](https://user-images.githubusercontent.com/16136908/29753637-4b602f22-8b93-11e7-870a-68205886f53e.png)

**Comment by joshsoucie** [comment]
Pull Request #71 should've fixed this.

Update from master & check again

**Comment by Akatsuki06** [comment]
Ok! Thanks
