### ISSUE TITLE
Blog is broken

### ISSUE THREAD

**Issue by adishavit** [joshgerdes/jekyll-uno#78]
As I was pushing a new post, I suddenly noticed that my jeyll-uno blog is broken. Seems like its missing some files that should be there - which I haven't really touched recently. 
It's as if something messed up the Jekyll paths.

I'm not really a web-dev, so I don't really know what to do to fix this.
- [Here's an example post](http://videocortex.io/2017/opencv-web-app/).
- My repo is [here](https://github.com/adishavit/adishavit.github.io).

![image](https://user-images.githubusercontent.com/1814800/30033671-34aa291e-91a5-11e7-98ea-bb848f37fe6f.png)

These are the console errors:

```
/2017/opencv-web-app/css/main.css?1504539877956271859 Failed to load resource: the server responded with a status of 404 (Not Found)
cover.jpg Failed to load resource: the server responded with a status of 404 (Not Found)
profile_100px.png Failed to load resource: the server responded with a status of 404 (Not Found)
main.js Failed to load resource: the server responded with a status of 404 (Not Found)
color_cycle_asm.js:1 pre-main prep time: 9 ms
printErr @ color_cycle_asm.js:1
main.js Failed to load resource: the server responded with a status of 404 (Not Found)
main.css Failed to load resource: the server responded with a status of 404 (Not Found)
```

Any ideas?

**Comment by adishavit** [comment]
I had to merge some of the fixes from master.

**Comment by adishavit** [comment]
Actually the problem persists.
The page is looking for `css/main.css` which does not exist anymore after the move to sass files.
I had to revert to an older version.

**Comment by PhilThurston** [comment]
Make sure your baseurl and url are both set properly in the _config.yml 

If that does not solve your issue take a look at your site source (right click on the site and select view source) and then find the line with your main.css. Post that line in this issue for further help

**Comment by adishavit** [comment]
It works OK on GitHUb (pre-latest merges) but not when locally hosted.
However, I changed `baseurl` from `'/'` to `''` and it now locally hosts OK.

I'll post another issue for the latest commits.
