### ISSUE TITLE
Uno theme bug in its baseurl setup

### ISSUE THREAD

**Issue by dfinke** [joshgerdes/jekyll-uno#85]
Hello,

This fix looks like it will fix my blog issues. How would go about merging all the changes from the last year so my theme is up to date?

Thank you.

https://github.com/joshgerdes/jekyll-uno/pull/71

https://dfinke.github.io/#blog
https://github.com/dfinke/dfinke.github.io

**Comment by joshgerdes** [comment]
You would pull the latest and, depending on what you changed, you would copy/merge the files over.
